[package]
name = "ImShot"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
windows = { version = "0.58.0", features = ["Win32", "Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_UI", "Win32_UI_WindowsAndMessaging", "Win32_UI_HiDpi"] }